# Navigation Menu in the Header
menu:
  Home: /
  Archives: /archives
  Youtube: http://www.youtube.com/pucechan
  Mixer: http://www.mixer.com/pucechan
  Twitch: http://twitch.tv/pucechan

# RSS URL
rss: /atom.xml

# use_cover (Use image in header)
use_cover: true
cover_image: /img/default_cover.png

widgets:
- category
- tag
- archive

# widget options
archive_type: 'monthly'
show_count: false

# favicon
favicon: /favicon.png

# Google Analytics Tracking ID
google_analytics: UA-368454-3